USE PRIMEIRO_BD

UPDATE CLIENTES
SET EMAIL = 'CONTATO@ALEXANDRE.COM.BR'
WHERE ID_CLIENTES = 1


UPDATE CLIENTES
SET 
	NOME = 'ALEXANDRE RODRIGUES 2',
	EMAIL = 'ALEXANDRERODRIGUES2@ALEXANDRE.COM'
WHERE
	ID_CLIENTES = 2


  SELECT * FROM CLIENTES
